AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  GetInfo:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler.get_info
      Runtime: python3.11
      Events:
        MyApi:
          Type: Api
          Properties:
            Path: /get-info
            Method: POST
